# Generated by Django 4.2.7 on 2025-12-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('gemini-2.0-flash-exp', 'Gemini 2.0 Flash (Experimental)'), ('gemini-1.5-flash', 'Gemini 1.5 Flash'), ('gemini-1.5-flash-8b', 'Gemini 1.5 Flash-8B'), ('gemini-1.5-pro', 'Gemini 1.5 Pro')], default='gemini-2.0-flash-exp', help_text='Gemini model to use (Flash models are free-tier friendly)', max_length=50)),
                ('api_key', models.CharField(blank=True, help_text='Google Gemini API key (optional if using .env)', max_length=500)),
                ('temperature', models.FloatField(default=0.7, help_text='0.0-1.0: Lower=deterministic, Higher=creative')),
                ('max_tokens', models.IntegerField(default=500, help_text='Maximum response length in tokens')),
                ('is_active', models.BooleanField(default=True, help_text='Use this configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gemini AI Configuration',
                'verbose_name_plural': 'Gemini AI Configurations',
            },
        ),
    ]
