# Generated by Django 6.0 on 2025-12-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_geminiconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeminiConfiguration',
        ),
    ]
