# Generated by Django 6.0 on 2025-12-14 17:37

import conference.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_abstractsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractsubmission',
            old_name='reason',
            new_name='admin_comments',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='research_interests',
        ),
        migrations.AddField(
            model_name='abstractsubmission',
            name='revised_submission',
            field=models.FileField(blank=True, null=True, upload_to=conference.models.submission_upload_path),
        ),
        migrations.AddField(
            model_name='abstractsubmission',
            name='revision_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='scientific_theme',
            field=models.CharField(choices=[('climate_change', 'Climate Change'), ('polar_biology', 'Polar Biology'), ('glaciology', 'Glaciology'), ('oceanography', 'Oceanography'), ('atmospheric_science', 'Atmospheric Science'), ('remote_sensing', 'Remote Sensing'), ('polar_geology', 'Polar Geology'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='abstractsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('recommended', 'Recommended'), ('revision', 'Revision Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
