# Generated by Django 6.0 on 2025-12-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_rename_reason_abstractsubmission_admin_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractsubmission',
            name='revised_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
