# Generated by Django 6.0 on 2025-12-15 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0004_abstractsubmission_revised_uploaded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='abstractsubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RECOMMENDED', 'Recommended'), ('REVISION', 'Revision Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='abstractsubmission',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abstracts', to='conference.scientifictheme'),
        ),
        migrations.CreateModel(
            name='ThemeAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('themes', models.ManyToManyField(related_name='theme_admins', to='conference.scientifictheme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
