# Generated by Django 6.0 on 2025-12-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0005_scientifictheme_alter_abstractsubmission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractsubmission',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abstracts', to='conference.scientifictheme'),
        ),
    ]
