# Generated by Django 6.0 on 2025-12-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0006_alter_abstractsubmission_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractsubmission',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
