# Generated by Django 6.0 on 2025-12-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0007_alter_abstractsubmission_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractsubmission',
            name='revised_abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
