# Generated by Django 6.0 on 2025-12-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='conference.abstractsubmission')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to='conference.themeadmin')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('abstract', 'reviewer')},
            },
        ),
    ]
