# Generated by Django 6.0 on 2025-12-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0010_abstractreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractreview',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='abstractreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='abstractreview',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstractreview',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
