# Generated by Django 6.0 on 2025-12-18 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0012_adminactionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractreview',
            name='created_at',
        ),
        migrations.AddField(
            model_name='abstractreview',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION', 'Revision Required')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='abstractreview',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractreview',
            name='comment',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abstractreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference.themeadmin'),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ASSIGN', 'Assign Reviewer'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
