# Generated by Django 6.0 on 2025-12-18 23:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0013_remove_abstractreview_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractreview',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_reviews', to='conference.themeadmin'),
        ),
        migrations.AddField(
            model_name='abstractreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='abstractreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reviews', to='conference.themeadmin'),
        ),
        migrations.AlterField(
            model_name='abstractreview',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('RECOMMENDED', 'Recommended'), ('REVISION', 'Revision Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMITTED', 'Resubmitted')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='abstractreview',
            unique_together={('abstract', 'reviewer')},
        ),
    ]
