# Generated by Django 6.0 on 2025-12-25 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0014_abstractreview_assigned_by_abstractreview_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractsubmission',
            name='revised_abstract',
        ),
        migrations.AlterField(
            model_name='abstractreview',
            name='status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approve'), ('REVISION', 'Revision Required'), ('REJECTED', 'Reject')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adminactionlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
