# Generated by Django 6.0 on 2026-01-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0015_remove_abstractsubmission_revised_abstract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='title',
            field=models.CharField(blank=True, choices=[('', ''), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Mx', 'Mx'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abstractsubmission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVISION', 'Revision Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
