# Generated by Django 6.0 on 2026-01-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0016_participant_title_alter_abstractsubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
